In [113]:
import pandas as pd
import os

In [114]:
df = pd.read_csv('multiple_courses_modules2.csv')

In [115]:
# Define the output directory
output_dir = 'courses_separated'
os.makedirs(output_dir, exist_ok=True)

# Group by the 'course' column to handle courses with multiple rows
grouped_courses = df.groupby('Course')

# Iterate over each course group
for course_name, group in grouped_courses:
    modules = []

    # For each group (course), combine modules from year 1 to year 4
    for year in ['Level 1', 'Level 3', 'Level 2', 'Level 4']:
        if year in df.columns:
            for module in group[year].dropna():  # Drop NaN values
                modules.extend(module.split(','))  # Split modules by commas if they are comma-separated

    # Remove any extra spaces
    modules = [module.strip() for module in modules if module.strip()]  # Also remove empty strings

    # If there are any modules collected, save them
    if modules:
        # Create a new DataFrame with the combined modules for the course
        modules_df = pd.DataFrame(modules, columns=['Modules'])

        # Save each course's modules to a CSV file, named after the course
        course_file_name = f"{course_name.replace(' ', '_')}_modules.csv"
        modules_df.to_csv(os.path.join(output_dir, course_file_name), index=False)

        # Display the DataFrame in Jupyter Notebook for verification
        print(f"Modules for {course_name}:")
        display(modules_df)  # Use display in Jupyter Notebook to see the DataFrame

Modules for Computer Networks:

                                              Modules
0                    Introduction to Computer Science
1                           Mathematics for Computing
2                                    Programming in C
3                            Professional Development
4                    Data communications and networks
5               Object-Oriented Programming with Java
6                      Algorithms and Data structures
7                               Computer Architecture
8                         Database Management Systems
9                   Web-Based Application Development
10                                         Internship
11                 Information Assurance and Security
12            Social Issues and Professional Practice
13      Wireless Technologies and Network Programming
14                 Advanced Mathematics for Computing
15                              IT Project Management
16                               IT Audit and Control
17                            Enterprise Architecture
18                     Advanced Routing and Switching
19              Service provider systems and networks
20                                       Cryptography
21                                  Computer Networks
22                        Systems Analysis and Design
23                           Statistics for Computing
24           Development of Enterprise Applications I
25                         Human-Computer Interaction
26                                 Network Management
27                            Voice and Video over IP
28   Network systems configuration and administration
29                                   Network Security
30                                  Operating Systems
31                           CN Honours Award Project
32                         Platform-Based Development
33                   Data Warehousing and Data Mining
34                                 Internet of Things
35                       Business Policy and Strategy
36                                Enterprise Networks
37                 E-Business Application Development
38                                   Entrepreneurship
39                     Management Information Systems
40                                   Embedded Systems
41  Disaster Recovery and High availability Techni...
42                               Intrusion Prevention
43                               Detection & Response
44                 Parallel and Distributed Computing

Modules for Computer Science:

                                          Modules
0                Introduction to Computer Science
1                       Mathematics for Computing
2                                Programming in C
3                        Professional Development
4                Data communications and networks
5           Object Oriented Programming with Java
6                  Algorithms and Data Structures
7                           Computer Architecture
8                     Database Management Systems
9               Web Based Application Development
10                                     Internship
11             Information Assurance and Security
12        Social Issues and Professional Practice
13  Wireless Technologies and Network Programming
14             Advanced Mathematics for Computing
15                           Computational Theory
16      Programming Languages and Compiler Design
17           Advanced Database Management Systems
18                                   Cryptography
19                 Mobile Application Development
20                    Software Process Management
21                              Computer Networks
22                    Systems Analysis and Design
23                       Statistics for Computing
24       Development of Enterprise Applications I
25                     Human-Computer Interaction
26                     Business Processes and ERP
27           Introduction to Software Engineering
28                          Software Architecture
29                      Algorithms and Complexity
30                              Operating Systems

Modules for Data Science:

                                      Modules
0            Introduction to Computer Science
1                   Mathematics for Computing
2                            Programming in C
3                 Database Management Systems
4                    Professional Development
5       Object Oriented Programming with Java
6              Algorithms and Data Structures
7       Fundamentals of Computer Architecture
8             Data Communication and Networks
9           Web Based Application Development
10                                 Web Mining
11       Advanced Statistics for Data Science
12             Data Warehousing & Data Mining
13                         Data Visualization
14       Advanced database Management Systems
15         Information Assurance and Security
16                                 Internship
17                            Cloud Computing
18                           Machine Learning
19             Mobile Application Development
20                         Big Data Analytics
21               Introduction to Data Science
22                 Human Computer Interaction
23                    Data Programming with R
24                Statistics for Data Science
25       Introduction to Software Engineering
26   Development of Enterprise Applications I
27                        System Fundamentals
28                  Algorithms and Complexity
29                     Data Science in Python
30                     Ethics in Data Science
31                Natural Language Processing
32                            Neural Networks
33                       Big Data Programming
34                    DS Honors Award Project
35                            Urban Computing
36                    Artificial Intelligence
37       Data Science Trends and Applications
38                              Deep Learning
39         Parallel and Distributed Computing
40                         Internet of Things
41  Development of Enterprise Applications II

Modules for Management Information Systems:

                                              Modules
0                    Introduction to Computer Science
1                           Mathematics for Computing
2                                    Programming in C
3                            Professional Development
4                    Data communications and networks
5               Object-Oriented Programming with Java
6                      Algorithms and Data structures
7                               Computer Architecture
8                         Database Management Systems
9                   Web-Based Application Development
10                                         Internship
11                 Information Assurance and Security
12            Social Issues and Professional Practice
13      Wireless Technologies and Network Programming
14                              IT Project Management
15                               IT Audit and Control
16               Advanced Database Management Systems
17                            Enterprise Architecture
18                         Software Quality Assurance
19                     Mobile Application Development
20                        Software Process Management
21                                  Computer Networks
22                        Systems Analysis and Design
23                           Statistics for Computing
24           Development of Enterprise Applications I
25                         Human-Computer Interaction
26                         Business Processes and ERP
27               Introduction to Software Engineering
28                              Software Architecture
29                          Algorithms and Complexity
30                                  Operating Systems
31                          MIS Special Award Project
32                         Platform-Based Development
33                   Data Warehousing and Data Mining
34                                 Internet of Things
35                       Business Policy and Strategy
36                                Enterprise Networks
37                 E-Business Application Development
38                                Agent-Based Systems
39                                   Entrepreneurship
40                     Management Information Systems
41          Development of Enterprise Applications II
42  Disaster Recovery and High availability Techni...
43                                 Business Analytics

Modules for Software Engineering:

                                      Modules
0            Introduction to Computer Science
1                   Mathematics for Computing
2                            Programming in C
3                    Professional Development
4            Data communications and networks
5       Object-Oriented Programming with Java
6              Algorithms and Data structures
7                       Computer Architecture
8                 Database Management Systems
9           Web-Based Application Development
10                                 Internship
11         Information Assurance and Security
12    Social Issues and Professional Practice
13       Software Verification and Validation
14         Advanced Mathematics for Computing
15       Advanced Database Management Systems
16             Mobile Application Development
17                Software Process Management
18                      IT Project Management
19                          Computer Networks
20                Systems Analysis and Design
21                   Statistics for Computing
22   Development of Enterprise Applications I
23                 Human-Computer Interaction
24                 Business Processes and ERP
25       Introduction to Software Engineering
26                      Software Architecture
27                  Algorithms and Complexity
28                          Operating Systems
29                   SE Honours Award Project
30                 Platform-Based Development
31           Data Warehousing and Data Mining
32                         Internet of Things
33               Business Policy and Strategy
34                        Enterprise Networks
35         E-Business Application Development
36                        Agent-Based Systems
37             Management Information Systems
38  Development of Enterprise Applications II
39        Computer Graphics and Visualization
40                    Artificial Intelligence
41         Parallel and Distributed Computing
42                           Embedded Systems